Rbac/Controllers/GetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rbac.Models;
using Rbac.Filters;

namespace Rbac.Controllers
{
    [CustomAuthrozi(AuthorizationType=AuthorizationType.None)]
    public class GetController : Controller
    {
        RbacDb db = new RbacDb();
        // GET: Get
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Reg(User regUser)
        {
            if(!ModelState.IsValid)
            {
                return Json(new { code = 400 });
            }

           try
            {
                //获取要增加的角色实体
                var role = db.Roles.FirstOrDefault(r => r.Id == 3);
                //给用户增加角色
                regUser.Roles.Add(role);
                //把注册用户添加到用户表
                db.Users.Add(regUser);
                //保存到数据库
                db.SaveChanges();
            }
            catch(Exception)
            {
                return Json(new { code = 404 });
            }

            return Json(new { code = 200 });
        }
    }
}

Rbac/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rbac.Models;
using Rbac.Filters;

namespace Rbac.Controllers
{
    [CustomAuthrozi(AuthorizationType =AuthorizationType.None)]
    public class LoginController : Controller
    {
        RbacDb db = new RbacDb();
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login(User loginUser)
        {
            //模型绑定验证
            if(!ModelState.IsValid)
            {
                return Json(new { code = 400 });
            }
            //查找用户
            var user = db.Users.FirstOrDefault(
                u => u.UserName == loginUser.UserName && u.PassWord == loginUser.PassWord);
            //如果没找到，就返回404
            if (user == null) return Json(new { code = 404 });
            //设置Sessio，作为身份验证的标识
            Session["user"] = user;


            /*第一种方式，支持多角色选择
             * 
            //获取所有角色的所有模块，转换成字典类，key是脚色的id。value是角色所有用的模块集合
            var roleModules = user.Roles.ToDictionary(r => r.Id, r => r.Modules);
            //存入到session，之后在复用，不用再查数据库。
            Session["roleModules"] = roleModules;


            //获取用户角色表
            var roles = user.Roles.ToList();
            //存入到session，以使之后复用
            Session["roles"] = roles;
            //设置默认角色为用户角色表里的第一个
            Session["rele"] = roles[0];
            */

            //Func泛型委托
            //Func<T,T,......TResult>


            //第二种形式，内联委托
            //Func<Role, bool> func1 = delegate (Role role1)
            //   {
            //       if (role1.Id == 3) return true;
            //       return false;
            //   };

            //第三种形式，lambda表达式代替内联委托
            //Func<Role, bool> func1 = robe1 =>
            //  {
            //      return true;
            //  };


            //第四种形式，简化了lambda表达式的方法体，如果只有一句返回值的语句，就可以省略掉{}和return
           //  Func<Role, bool> func1 = robe1 => true;

            //r=>true  就是只拿第一条
            var role = user.Roles.FirstOrDefault(robe1 => true);

            Session["role"] = role;

            return Json(new { code = 200 });


            //Take(1)，就是从一个集合里，只拿出一条数据
           // Session["role"] = user.Roles.Take(1);

            //return Json(new { code = 200 });
        }
        /// <summary>
        /// 第一种委托形式，创建一个方法，传给委托
        /// </summary>
        /// <param name="role1"></param>
        /// <returns></returns>
        private bool Func1(Role role1)
        {
            if (role1.Id == 3) return true;
            return false;
        }
    }
}

Rbac/Controllers/homeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rbac.Filters;
using Rbac.Models;

namespace Rbac.Controllers
{
    [CustomAuthrozi(AuthorizationType = AuthorizationType.Identity)]
    public class homeController : Controller
    {
        // GET: home
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 头部的分部试图
        /// </summary>
        /// <returns></returns>
        public ActionResult Header()
        {
            /* 第一种方式，选择角色
            var user = Session["user"] as User;
            var roles = Session["roles"] as List<Role>;
            var role = Session["role"] as Role;

            List<SelectListItem> roleList = new List<SelectListItem>();
            foreach(var item in roles)
            {
                roleList.Add(new SelectListItem { Text = item.Name, Value = item.Id.ToString(), Selected = item.Id == role.Id });
            }

            ViewBag.roleList = roleList;
             return PartialView(user);
            */
            var user = Session["user"] as User;
            var role = Session["role"] as Role;
            ViewBag.UserName = user.UserName;
            //不确定对错
            ViewBag.RoleName = role.Name;

            return PartialView();
        }
        /// <summary>
        /// 导航栏的分部试图
        /// 负责查询你所选择的角色的所有模块
        /// 并且把所有的模块渲染出来
        /// </summary>
        /// <returns></returns>
        public ActionResult Nav(int roleId=0)
        {
            //第一种方式，可选择用户角色
            //获取session里的用户角色模块表
            // var roleModules = Session["roleModules"] as Dictionary<int, ICollection<Module>>;
            //获取session里默认的角色
            //  var role = Session["role"] as Role;
            //  var roles = Session["roles"] as List<Role>;


            //根据参数里roleId，获取某一个用户角色的模块表
            //List<Module> modules;
            //if(roleModules.ContainsKey(roleId))
            //{
            //    modules = roleModules[roleId].ToList();
            //    //切换当前角色
            //    Session["role"] = roles[roleId];
            //}
            //else
            //{
            //    modules = roleModules[role.Id].ToList();
            //}


            //var modules = roleModules[roleId];

            //如果模块表为Null，说明当前传递的roleId有误
            //if(modules==null)
            //{
            //就使用session里的roleId
            //    modules = roleModules[role.Id];
            //}

            //第二种角色，只是用默认角色，不选择

            //获取session里默认的角色
            var role = Session["role"] as Role;
            //从默认角色里获取模块
            var modules = role.Modules;


            return PartialView(modules);
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index", "Login");
        }
    }
}

Rbac/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>RBAC Demo - 登陆</title>
    <script src="~/Scripts/jquery-3.2.1.js"></script>
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <link href="~/content/login.css" rel="stylesheet" />
</head>
<body>
    <div id="login">
        <span class="form-title">登陆</span>

        <form action="#" method="post">
            <div class="form-item">
                <label>账号:</label>
                <input type="text" name="UserName" />
            </div>

            <div class="form-item">
                <label>密码:</label>
                <input type="password" name="PassWord" />
            </div>
            <input class="btn" type="button" value="登陆" />
        </form>
    </div>
    @*<span class="form-title">注册</span>*@
    @Html.ActionLink("注册","Index","Get")
    <script>
        $(function () {
            $(".btn").click(function () {
                var username = $("input[name=UserName]").val();
                var password = $("input[name=PassWord]").val();

                if (username === "" || password === "") {
                    alert("账号密码不能为空");
                    return;
                }

                $.ajax({
                    url: "@Url.Action("Login")",
                    type: "post",
                    data: $("form").serialize(),
                    success: function (res) {
                        if (res.code === 200) {
                            window.location = "@Url.Action("Index","home")"
                        } else if (res.code === 400) {
                            alert("非法参数");
                        } else {
                            alert("登陆失败，账号或密码错误");
                        }
                    }
                })
            })
        })
       
    </script>
</body>
</html>